version: '3.8'
services:
  devops_project:
    image: devops_project
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8700:8082"
    depends_on:
      - postgres_app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_app:5432/devopsDB
      - SPRING_PROFILES_ACTIVE=prod

  postgres_app:
    image: postgres_app:latest
    networks:
      - mynetwork
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: devopsTestDB
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres-data: