version: "24.0.6"
services:
  AppBack:
    image: devops_project
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8700:8082"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5434/devopsTestDB
      - SPRING_PROFILES_ACTIVE=test

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: devopsTestDB
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge

volumes:
  postgres-data: